# The URL the site will be built for
base_url = "https://nonmodernist.com/dcda30970"
title = "DCDA 30970"
description = "Special Topics in Digital Culture"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

 taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
       {name = "categories", paginate_by = 5},  # 5 items per page for a term
{name = "authors"}, # Basic definition: no feed or pagination
    ]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"
external_links_class = "external-link"
external_links_target_blank = true
smart_punctuation = true
bottom_footnotes = true
insert_anchor_links = "heading"

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the RFC3339 datetime of the page in the search index
include_date = false
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which code point to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100

# Whether to produce the search index as a javascript file or as a JSON file
# Accepted values:
# - "elasticlunr_javascript", "elasticlunr_json"
# - "fuse_javascript", "fuse_json"
index_format = "elasticlunr_javascript"




[extra]
# Put all your custom variables here
